export type Candidate = {
  id: string
  name: string
  category: string
  description: string
  votes: number
  imageUrl: string
}

export type Category = {
  id: string
  name: string
}

// Define categories
export const categories: Category[] = [
  { id: "1", name: "Media" },
  { id: "2", name: "Social Media Influence" },
  { id: "3", name: "Politics & Governance" },
  { id: "4", name: "Human Rights & Social Justice" },
  { id: "5", name: "Corporate" },
  { id: "6", name: "Healthcare" },
  { id: "7", name: "Education, Training & Development" },
  { id: "8", name: "Youth & Innovation" },
  { id: "9", name: "Gender Equality" },
  { id: "10", name: "Money & Business" },
  { id: "11", name: "Manufacturing & Industrialization" },
  { id: "12", name: "Hospitality & Tourism" },
  { id: "13", name: "Agriculture & Climate Change" },
  { id: "14", name: "Sports" },
  { id: "15", name: "Tech and Entrepreneurship" },
  { id: "16", name: "Real Estate & Development" },
  { id: "17", name: "People With Disability & Minority" },
  { id: "18", name: "Entertainment & Creative Arts" },
  { id: "19", name: "Diaspora Impact" },
  { id: "20", name: "Lifetime Achievement" },
]

// Generate candidates based on the provided list
export function generateCandidates(): Candidate[] {
  return [
    // 1. Media
    {
      id: "1-1",
      name: "Lynne Ngugi",
      category: "1",
      description: "LN Media",
      votes: 0,
      imageUrl: "/images/Lynne Ngugi.jpg",
    },
    {
      id: "1-2",
      name: "Yvonne Okwara",
      category: "1",
      description: "Media Personality",
      votes: 0,
      imageUrl: "/images/Yvonne Okwara.jpg",
    },
    {
      id: "1-3",
      name: "Mashirima Kapombe",
      category: "1",
      description: "Media Personality",
      votes: 0,
      imageUrl: "/images/Mashirima Kapombe.jpg",
    },
    {
      id: "1-4",
      name: "Adelle Onyango",
      category: "1",
      description: "Media Personality",
      votes: 0,
      imageUrl: "/images/adele-onyango.png",
    },
    {
      id: "1-5",
      name: "Pamela Sittoni",
      category: "1",
      description: "Media Personality",
      votes: 0,
      imageUrl: "/images/Pamela Sittoni.jpg",
    },
    {
      id: "1-6",
      name: "Zubeida Koome",
      category: "1",
      description: "Media Personality",
      votes: 0,
      imageUrl: "/images/Zubeida Koome.jpg",
    },
    {
      id: "1-7",
      name: "Victoria Rubadiri",
      category: "1",
      description: "Media Personality",
      votes: 0,
      imageUrl: "/images/Victoria Rubadiri.jpg",
    },
    {
      id: "1-8",
      name: "Mwende Macharia",
      category: "1",
      description: "Media Personality",
      votes: 0,
      imageUrl: "/images/Mwende Macharia.jpg",
    },

    // 2. Social Media Influence
    {
      id: "2-1",
      name: "Ajib Gathoni",
      category: "2",
      description: "Social Media Influencer",
      votes: 0,
      imageUrl: "/images/ajib-gathoni.png",
    },
    {
      id: "2-2",
      name: "Diana Marua",
      category: "2",
      description: "Social Media Influencer",
      votes: 0,
      imageUrl: "/images/diana-marua.png",
    },
    {
      id: "2-3",
      name: "Eve Mungai",
      category: "2",
      description: "Social Media Influencer",
      votes: 0,
      imageUrl: "/images/eve-mungai.png",
    },
    {
      id: "2-4",
      name: "Esther Akoth (Akothee)",
      category: "2",
      description: "Social Media Influencer",
      votes: 0,
      imageUrl: "/images/esther-akoth.png",
    },
    {
      id: "2-5",
      name: "Debby Rono",
      category: "2",
      description: "Comedian and Mental Health Advocate",
      votes: 0,
      imageUrl: "/images/debby-ronoh.png",
    },
    {
      id: "2-6",
      name: "Hanifa Farsafi",
      category: "2",
      description: "Social Media Influencer",
      votes: 0,
      imageUrl: "/images/Hanifa Farsafi.jpg",
    },
    {
      id: "2-7",
      name: "Miss Muthoni",
      category: "2",
      description: "The LinkedIn Lionness",
      votes: 0,
      imageUrl: "/images/Ms. Muthoni Njoroge.jpg",
    },

    // 3. Politics & Governance
    {
      id: "3-1",
      name: "Anne Waiguru",
      category: "3",
      description: "Politician",
      votes: 0,
      imageUrl: "/images/anne-waiguru.png",
    },
    {
      id: "3-2",
      name: "Fatuma Achani",
      category: "3",
      description: "Governor Kwale County",
      votes: 0,
      imageUrl: "/images/fatuma-achani.png",
    },
    {
      id: "3-3",
      name: "Gladys Wanga",
      category: "3",
      description: "Politician",
      votes: 0,
      imageUrl: "/images/Gladys Wanga.jpg",
    },
    {
      id: "3-4",
      name: "Margaret Nyakango",
      category: "3",
      description: "Budget Controller: Courage",
      votes: 0,
      imageUrl: "/images/Margaret Nyakang'o.jpg",
    },
    {
      id: "3-5",
      name: "Gathoni wa Muchomba",
      category: "3",
      description: "Politician",
      votes: 0,
      imageUrl: "/images/Gathoni Wa Muchomba.jpg",
    },
    {
      id: "3-6",
      name: "Jane Njeri Maina",
      category: "3",
      description: "Politician",
      votes: 0,
      imageUrl: "/images/Jane Njeri Maina.jpg",
    },
    {
      id: "3-7",
      name: "Millie Odhiambo",
      category: "3",
      description: "Politician",
      votes: 0,
      imageUrl: "/images/Millie Odhiambo.jpg",
    },
    {
      id: "3-8",
      name: "CJ Martha Koome",
      category: "3",
      description: "Chief Justice",
      votes: 0,
      imageUrl: "/images/cj-martha-koome.png",
    },

    // 4. Human Rights & Social Justice
    {
      id: "4-1",
      name: "Gloria Orwoba",
      category: "4",
      description: "Period Poverty Advocate",
      votes: 0,
      imageUrl: "/images/Gloria Omwomba.jpg",
    },
    {
      id: "4-2",
      name: "Nerima Wako Ojiwa",
      category: "4",
      description: "Cost of living Advocate",
      votes: 0,
      imageUrl: "/images/Nerima Wako.jpg",
    },
    {
      id: "4-3",
      name: "Faith Odhiambo",
      category: "4",
      description: "LSK",
      votes: 0,
      imageUrl: "/images/faith-odhiambo.png",
    },
    {
      id: "4-4",
      name: "Njeri wa Migwi",
      category: "4",
      description: "Feminist Human Rights Defender",
      votes: 0,
      imageUrl: "/images/Njeri wa Migwi.jpg",
    },
    {
      id: "4-5",
      name: "Mercy Odondo",
      category: "4",
      description: "SRHR/SGBV Advocate",
      votes: 0,
      imageUrl: "/images/Mercy Odondo.jpg",
    },

    // 5. Corporate
    {
      id: "5-1",
      name: "Jane Karuku",
      category: "5",
      description: "CEO EABL",
      votes: 0,
      imageUrl: "/images/jane-karuku.png",
    },
    {
      id: "5-2",
      name: "Rita Kavashe",
      category: "5",
      description: "Isuzu",
      votes: 0,
      imageUrl: "/images/Rita Kavashe.jpg",
    },
    {
      id: "5-3",
      name: "Laila Macharia",
      category: "5",
      description: "CENTUM",
      votes: 0,
      imageUrl: "/images/Laila Macharia.jpg",
    },
    {
      id: "5-4",
      name: "Dorothy Ghettuba Pala",
      category: "5",
      description: "Netflix Manager International Originals",
      votes: 0,
      imageUrl: "/images/dorothy-ghettuba.png",
    },
    {
      id: "5-5",
      name: "Eva Muraya",
      category: "5",
      description: "BSD Group",
      votes: 0,
      imageUrl: "/images/eva-muraya.png",
    },
    {
      id: "5-6",
      name: "Mary Mulili",
      category: "5",
      description: "UBA Kenya Designate Managing Director and CEO",
      votes: 0,
      imageUrl: "/images/Mary Mulili.jpg",
    },
    {
      id: "5-7",
      name: "Joan the Career Coach",
      category: "5",
      description: "Career Coach",
      votes: 0,
      imageUrl: "/images/placeholder-profile.png",
    },
    {
      id: "5-8",
      name: "Lucia Musau",
      category: "5",
      description: "Corporate Leader",
      votes: 0,
      imageUrl: "/images/Lucia Musau.jpg",
    },

    // 6. Healthcare
    {
      id: "6-1",
      name: "Dr. Lizzie Itotia",
      category: "6",
      description: "Healthcare Professional",
      votes: 0,
      imageUrl: "/images/dr-lizzie-itotia.png",
    },
    {
      id: "6-2",
      name: "Anna Qabale Duba",
      category: "6",
      description: "Global Nursing Award",
      votes: 0,
      imageUrl: "/images/anne-qabale-duba.png",
    },
    {
      id: "6-3",
      name: "Stella Wairimu Bosire",
      category: "6",
      description: "CEO Kenya Medical Association",
      votes: 0,
      imageUrl: "/images/Stellah Wairimu Bosire.jpg",
    },

    // 7. Education, Training & Development
    {
      id: "7-1",
      name: "Mumbi Ndung'u",
      category: "7",
      description: "Executive Director Power Learn Project",
      votes: 0,
      imageUrl: "/images/Mumbi Ndung'u.jpg",
    },
    {
      id: "7-2",
      name: "Prof. Nancy Booker",
      category: "7",
      description: "Education Professional",
      votes: 0,
      imageUrl: "/images/Prof. Nancy Booker.jpg",
    },
    {
      id: "7-3",
      name: "Rosalia Mkanjala",
      category: "7",
      description: "KNUT",
      votes: 0,
      imageUrl: "/images/Rosalia Mkanjala.jpg",
    },
    {
      id: "7-4",
      name: "Wawira Njiru",
      category: "7",
      description: "Food for education",
      votes: 0,
      imageUrl: "/images/Wawira Njiru.jpg",
    },
    {
      id: "7-5",
      name: "Nelly Cheboi",
      category: "7",
      description: "CNN Person of the Year",
      votes: 0,
      imageUrl: "/images/Nelly Cheboi.jpg",
    },

    // 8. Youth & Innovation
    {
      id: "8-1",
      name: "Caren Wakoli",
      category: "8",
      description: "Founder and Executive Director of Emerging Leaders",
      votes: 0,
      imageUrl: "/images/caren-wakoli.png",
    },
    {
      id: "8-2",
      name: "Nancy Maina",
      category: "8",
      description: "Founder Lugha Ishara",
      votes: 0,
      imageUrl: "/images/Nancy Maina.jpg",
    },
    {
      id: "8-3",
      name: "Angela Oduor Lungati",
      category: "8",
      description: "Youth & Innovation Leader",
      votes: 0,
      imageUrl: "/images/angela-oduor-langat.png",
    },
    {
      id: "8-4",
      name: "Esther Ndeti",
      category: "8",
      description: "Youth & Innovation Leader",
      votes: 0,
      imageUrl: "/images/esther-ndeti.png",
    },
    {
      id: "8-5",
      name: "Beth Koigi",
      category: "8",
      description: "Majik Water",
      votes: 0,
      imageUrl: "/images/beth-koigi.png",
    },
    {
      id: "8-6",
      name: "Sheryl Mboya",
      category: "8",
      description: "Edible Plate",
      votes: 0,
      imageUrl: "/images/Sheryll Mboya.jpg",
    },

    // 9. Gender Equality
    {
      id: "9-1",
      name: "Anne Ireri",
      category: "9",
      description: "CEO of FIDA",
      votes: 0,
      imageUrl: "/images/anne-ireri.png",
    },
    {
      id: "9-2",
      name: "Dorcas Gachagua",
      category: "9",
      description: "Mama Boys: Second Lady",
      votes: 0,
      imageUrl: "/images/dorcas-rigathi.png",
    },
    {
      id: "9-3",
      name: "PS Wangombe",
      category: "9",
      description: "Gender Equality Advocate",
      votes: 0,
      imageUrl: "/images/PS Ann Wang'ombe.jpg",
    },

    // 10. Money & Business
    {
      id: "10-1",
      name: "Dr Joyce Gikunda",
      category: "10",
      description: "Linton's Beauty",
      votes: 0,
      imageUrl: "/images/dr-joyce-gikunda.png",
    },
    {
      id: "10-2",
      name: "Mary Muthoni Jason",
      category: "10",
      description: "Women in Business (WIB) Kenya CEO, PS Prisons and Correctional Services",
      votes: 0,
      imageUrl: "/images/Mary Muthoni Jason.jpg",
    },
    {
      id: "10-3",
      name: "Ann Mathu",
      category: "10",
      description: "NACADA",
      votes: 0,
      imageUrl: "/images/ann-mathu.png",
    },
    {
      id: "10-4",
      name: "Dr Susan Onyancha",
      category: "10",
      description: "BF Suma",
      votes: 0,
      imageUrl: "/images/Susan Onyancha.jpg",
    },
    {
      id: "10-5",
      name: "Just Ivy Africa",
      category: "10",
      description: "Business Leader",
      votes: 0,
      imageUrl: "/images/Just-Ivy-Africa-.png",
    },

    // 11. Manufacturing & Industrialization
    {
      id: "11-1",
      name: "Flora Mutahi",
      category: "11",
      description: "Association of Manufacturing",
      votes: 0,
      imageUrl: "/images/flora-mutahi.png",
    },
    {
      id: "11-2",
      name: "Caroline Kariuki",
      category: "11",
      description: "KEPSA",
      votes: 0,
      imageUrl: "/images/caroline-kariuki.png",
    },
    {
      id: "11-3",
      name: "Mary Ngechu",
      category: "11",
      description: "Founder Plast Packaging Industries Limited",
      votes: 0,
      imageUrl: "/images/Mary-Ngechu.png",
    },

    // 12. Hospitality & Tourism
    {
      id: "12-1",
      name: "Sarah Kabu",
      category: "12",
      description: "Bonfire",
      votes: 0,
      imageUrl: "/images/Sarah-Kabu.png",
    },
    {
      id: "12-2",
      name: "Captain Ruth Karauri",
      category: "12",
      description: "Hospitality & Tourism Professional",
      votes: 0,
      imageUrl: "/images/captain-ruth-karauri.png",
    },
    {
      id: "12-3",
      name: "Dr Betty Adero Radier",
      category: "12",
      description: "Kenya Tourism Board CEO",
      votes: 0,
      imageUrl: "/images/dr-betty-adero.png",
    },

    // 13. Agriculture & Climate Change
    {
      id: "13-1",
      name: "Jamila Abbas",
      category: "13",
      description: "Poptech 2012",
      votes: 0,
      imageUrl: "/images/Jamila-Abbas.png",
    },
    {
      id: "13-2",
      name: "Judy Matu",
      category: "13",
      description: "Association of Women in Agriculture (AWAK)",
      votes: 0,
      imageUrl: "/images/dr-judy-matu.png",
    },
    {
      id: "13-3",
      name: "Daphne Muchai",
      category: "13",
      description: "Executive Director - Women Farmers Association of Kenya- WoFaAK",
      votes: 0,
      imageUrl: "/images/daphine-muchai.png",
    },
    {
      id: "13-4",
      name: "Elizabeth Wanjiru Wathuti",
      category: "13",
      description: "Founder of the Green Generation Initiative",
      votes: 0,
      imageUrl: "/images/elizabeth-wathuti.png",
    },

    // 14. Sports
    {
      id: "14-1",
      name: "Faith Kipyegon",
      category: "14",
      description: "Athletics",
      votes: 0,
      imageUrl: "/images/faith-kipyegon.png",
    },
    {
      id: "14-2",
      name: "Angela Okutoyi",
      category: "14",
      description: "Tennis",
      votes: 0,
      imageUrl: "/images/angela-otukoyi.png",
    },
    {
      id: "14-3",
      name: "Mwanalima Adam Jereko",
      category: "14",
      description: "Football: Harambee Starlets",
      votes: 0,
      imageUrl: "/images/mwanalima-Adam-.png",
    },
    {
      id: "14-4",
      name: "Alexandra Ndolo",
      category: "14",
      description: "Fencing",
      votes: 0,
      imageUrl: "/images/alexandra-ndolo.png",
    },
    {
      id: "14-5",
      name: "Paula Munyi",
      category: "14",
      description: "Sharpshooter",
      votes: 0,
      imageUrl: "/images/Paula-Munyi.png",
    },
    {
      id: "14-6",
      name: "Janet Wanja",
      category: "14",
      description: "Volleyball",
      votes: 0,
      imageUrl: "/images/Janet-Wanja.png",
    },
    {
      id: "14-7",
      name: "Slyvia Gathoni",
      category: "14",
      description: "E-Games: Arrow Queen",
      votes: 0,
      imageUrl: "/images/Sylvia-Gathoni-Wahome.png",
    },
    {
      id: "14-8",
      name: "Lorna Abiero",
      category: "14",
      description: "Martial Arts",
      votes: 0,
      imageUrl: "/images/Lorna-Abiero.png",
    },

    // 15. Tech and Entrepreneurship
    {
      id: "15-1",
      name: "Dr. Chao Mbogho",
      category: "15",
      description: "Tech and Entrepreneurship Leader",
      votes: 0,
      imageUrl: "/images/dr-chao-mbogho.png",
    },
    {
      id: "15-2",
      name: "Susan Odhiambo",
      category: "15",
      description: "Tech leadership Group head, Digital transformation Equity Bank",
      votes: 0,
      imageUrl: "/images/Susan-Athiambo.png",
    },
    {
      id: "15-3",
      name: "Dorothy Ooko",
      category: "15",
      description: "Google Head Of Communications & Public Affairs, Africa",
      votes: 0,
      imageUrl: "/images/dorothy-ooko.png",
    },
    {
      id: "15-4",
      name: "Janet C. Kemboi",
      category: "15",
      description: "Communications Manager, Eastern Africa · Meta",
      votes: 0,
      imageUrl: "/images/Janet-C.-Kemboi.png",
    },

    // 16. Real Estate & Development
    {
      id: "16-1",
      name: "Leah Wambui",
      category: "16",
      description: "Cherriez Property",
      votes: 0,
      imageUrl: "/images/Leah-Wambui.png",
    },
    {
      id: "16-2",
      name: "Liz Njuguna",
      category: "16",
      description: "Risiih Investments",
      votes: 0,
      imageUrl: "/images/Liz-Njuguna.png",
    },
    {
      id: "16-3",
      name: "Robyn Emerson",
      category: "16",
      description: "Women in Real Estate President",
      votes: 0,
      imageUrl: "/images/Robyn-Emerson.png",
    },

    // 17. People With Disability & Minority
    {
      id: "17-1",
      name: "Crystal Asige",
      category: "17",
      description: "Disability Rights Advocate",
      votes: 0,
      imageUrl: "/images/crystal-asige.png",
    },
    {
      id: "17-2",
      name: "Naisula Lesuuda",
      category: "17",
      description: "Minority Rights Advocate",
      votes: 0,
      imageUrl: "/images/Naisula-Lesuuda.png",
    },
    {
      id: "17-3",
      name: "Wanja Maina",
      category: "17",
      description: "Disability Rights Advocate",
      votes: 0,
      imageUrl: "/images/Wanja-Maina.png",
    },

    // 18. Entertainment & Creative Arts
    {
      id: "18-1",
      name: "Nikita Kering",
      category: "18",
      description: "Entertainment & Creative Arts Professional",
      votes: 0,
      imageUrl: "/images/Nikita-Kering.png",
    },
    {
      id: "18-2",
      name: "Jacky Vike",
      category: "18",
      description: "Entertainment & Creative Arts Professional",
      votes: 0,
      imageUrl: "/images/jacky-Vike.png",
    },
    {
      id: "18-3",
      name: "Nadia Mukami",
      category: "18",
      description: "Entertainment & Creative Arts Professional",
      votes: 0,
      imageUrl: "/images/Nadia-Mukami.png",
    },
    {
      id: "18-4",
      name: "Catherine Kamau",
      category: "18",
      description: "Actress",
      votes: 0,
      imageUrl: "/images/catherine-kamau.png",
    },
    {
      id: "18-5",
      name: "Angela Ndambuki",
      category: "18",
      description: "Entertainment & Creative Arts Professional",
      votes: 0,
      imageUrl: "/images/angela-ndambuki.png",
    },
    {
      id: "18-6",
      name: "Sofiya Nzau",
      category: "18",
      description: "Mwaki song",
      votes: 0,
      imageUrl: "/images/Sofiya-Nzau.png",
    },
    {
      id: "18-7",
      name: "Wixx Mangutha",
      category: "18",
      description: "Entertainment & Creative Arts Professional",
      votes: 0,
      imageUrl: "/images/Wixx-Mangutha.png",
    },

    // 19. Diaspora Impact
    {
      id: "19-1",
      name: "Lupita Nyong'o",
      category: "19",
      description: "Actress",
      votes: 0,
      imageUrl: "/images/Lupita-Nyong'o.png",
    },
    {
      id: "19-2",
      name: "Lilian Seenoi-Barr",
      category: "19",
      description: "Council Woman in Northern Ireland",
      votes: 0,
      imageUrl: "/images/Lilian-Seenoi-Baar.png",
    },
    {
      id: "19-3",
      name: "Winfred Yavi",
      category: "19",
      description: "Bahrain Athlete",
      votes: 0,
      imageUrl: "/images/Winfred-Yavi.png",
    },

    // 20. Lifetime Achievement
    {
      id: "20-1",
      name: "Eunice Mathu",
      category: "20",
      description: "Parents Africa",
      votes: 0,
      imageUrl: "/images/eunice-mathu.png",
    },
    {
      id: "20-2",
      name: "Dr. Ida Odinga",
      category: "20",
      description: "Lifetime Achievement",
      votes: 0,
      imageUrl: "/images/Ida-Odinga.png",
    },
    {
      id: "20-3",
      name: "Hon. Martha Karua",
      category: "20",
      description: "Lifetime Achievement",
      votes: 0,
      imageUrl: "/images/Martha-Karua.png",
    },
    {
      id: "20-4",
      name: "Prof. Eddah Gachukia",
      category: "20",
      description: "Riara Group of Schools",
      votes: 0,
      imageUrl: "/images/Prof.-Eddah-Gachukia.png",
    },

    // Additional Candidates with Existing Images
    {
      id: "21-1",
      name: "Hanifa Farsafi",
      category: "3",
      description: "Politician",
      votes: 0,
      imageUrl: "/images/Hanifa Farsafi.jpg",
    },
    {
      id: "21-2",
      name: "Jane Thuo",
      category: "5",
      description: "Corporate Leader",
      votes: 0,
      imageUrl: "/images/Jane Thuo.jpg",
    },
    {
      id: "21-3",
      name: "Jitabi Suleiman",
      category: "4",
      description: "Human Rights Advocate",
      votes: 0,
      imageUrl: "/images/Jitabi Suleiman.jpg",
    },
    {
      id: "21-4",
      name: "Ms. Muthoni Njoroge",
      category: "5",
      description: "Corporate Leader",
      votes: 0,
      imageUrl: "/images/Ms. Muthoni Njoroge.jpg",
    },
    {
      id: "21-5",
      name: "Ndu Okoh",
      category: "8",
      description: "Youth & Innovation Leader",
      votes: 0,
      imageUrl: "/images/Ndu Okoh.jpg",
    },
    {
      id: "21-6",
      name: "Njerae",
      category: "18",
      description: "Entertainment & Creative Arts Professional",
      votes: 0,
      imageUrl: "/images/Njerae.jpg",
    },
    {
      id: "21-7",
      name: "Tinashe & Carol Gatimu",
      category: "12",
      description: "Hospitality & Tourism",
      votes: 0,
      imageUrl: "/images/Tinashe-&-Carol-Gatimu.png",
    },
    {
      id: "21-8",
      name: "Ann Mathu",
      category: "7",
      description: "Education Professional",
      votes: 0,
      imageUrl: "/images/ann-mathu.png",
    },
    {
      id: "21-9",
      name: "Ann Njogu",
      category: "4",
      description: "Human Rights Advocate",
      votes: 0,
      imageUrl: "/images/ann-njogu.png",
    },
    {
      id: "21-10",
      name: "Anne Qabale Duba",
      category: "6",
      description: "Healthcare Professional",
      votes: 0,
      imageUrl: "/images/anne-qabale-duba.png",
    },
    {
      id: "21-11",
      name: "Azeezah Hashim",
      category: "8",
      description: "Youth & Innovation Leader",
      votes: 0,
      imageUrl: "/images/azeezah-hashim.png",
    },
    {
      id: "21-12",
      name: "Bushra Sakshi",
      category: "9",
      description: "Gender Equality Advocate",
      votes: 0,
      imageUrl: "/images/bushra-sakshi.png",
    },
    {
      id: "21-13",
      name: "Captain Ruth Karauri",
      category: "14",
      description: "Aviation Sports",
      votes: 0,
      imageUrl: "/images/captain-ruth-karauri.png",
    },
    {
      id: "21-14",
      name: "Chief Justice Martha Koome",
      category: "3",
      description: "Chief Justice of Kenya",
      votes: 0,
      imageUrl: "/images/cj-martha-koome.png",
    },
    {
      id: "21-15",
      name: "Dr. Lizzie Itotia",
      category: "6",
      description: "Healthcare Professional",
      votes: 0,
      imageUrl: "/images/dr-lizzie-itotia.png",
    },
    {
      id: "21-16",
      name: "Ajib Gathoni",
      category: "9",
      description: "Gender Equality Advocate",
      votes: 0,
      imageUrl: "/images/ajib-gathoni.png",
    },
  ]
}

// Create a singleton instance of candidates
let candidates: Candidate[] | null = null

export function getCandidates(): Candidate[] {
  if (!candidates) {
    candidates = generateCandidates()
  }
  return candidates
}

// Function to vote for a candidate
export function voteForCandidate(candidateId: string): boolean {
  const allCandidates = getCandidates()
  const candidate = allCandidates.find((c) => c.id === candidateId)

  if (candidate) {
    candidate.votes += 1
    return true
  }

  return false
}
